[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OS2Valghalla"
authors = [{name = "Jesper Borup", email = "jesper.borup@preciofishbone.dk"}]
dynamic = ["version", "description"]
