[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OS2Valghalla"
authors = [{name = "OS2", email = "os2@os2.eu"}]
dynamic = ["version", "description"]
